/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TransactionMode = IDL.Variant({
  'ATM' : IDL.Null,
  'POS' : IDL.Null,
  'Web' : IDL.Null,
  'Mobile' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'OnlinePurchase' : IDL.Null,
  'Withdrawal' : IDL.Null,
  'Transfer' : IDL.Null,
  'Payment' : IDL.Null,
});
export const MerchantCategory = IDL.Variant({
  'Food' : IDL.Null,
  'Bills' : IDL.Null,
  'Travel' : IDL.Null,
  'Shopping' : IDL.Null,
  'Others' : IDL.Null,
});
export const DeviceType = IDL.Variant({
  'iOS' : IDL.Null,
  'Android' : IDL.Null,
  'Desktop' : IDL.Null,
});
export const CheckTransactionRequest = IDL.Record({
  'transactionMode' : TransactionMode,
  'transactionType' : TransactionType,
  'merchantCategory' : MerchantCategory,
  'deviceType' : DeviceType,
  'amount' : IDL.Float64,
  'location' : IDL.Text,
});
export const UserId = IDL.Principal;
export const AutoFeatures = IDL.Record({
  'avgAmount' : IDL.Float64,
  'txCount24h' : IDL.Nat,
  'timeSinceLast' : IDL.Int,
  'prevLocation' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'fraudReasons' : IDL.Vec(IDL.Text),
  'transactionMode' : TransactionMode,
  'transactionType' : TransactionType,
  'userId' : UserId,
  'autoFeatures' : AutoFeatures,
  'merchantCategory' : MerchantCategory,
  'isFraud' : IDL.Bool,
  'timestamp' : Timestamp,
  'deviceType' : DeviceType,
  'confidence' : IDL.Float64,
  'amount' : IDL.Float64,
  'location' : IDL.Text,
  'riskScore' : IDL.Float64,
});
export const DashboardStats = IDL.Record({
  'fraudCount' : IDL.Nat,
  'safeCount' : IDL.Nat,
  'recentTransactions' : IDL.Vec(Transaction),
  'fraudPercentage' : IDL.Float64,
  'totalTransactions' : IDL.Nat,
});
export const ModelMetrics = IDL.Record({
  'trueNegatives' : IDL.Nat,
  'fraudCount' : IDL.Nat,
  'truePositives' : IDL.Nat,
  'f1Score' : IDL.Float64,
  'safeCount' : IDL.Nat,
  'precision' : IDL.Float64,
  'falseNegatives' : IDL.Nat,
  'falsePositives' : IDL.Nat,
  'totalTransactions' : IDL.Nat,
  'recall' : IDL.Float64,
  'accuracy' : IDL.Float64,
});
export const UserBehaviorProfile = IDL.Record({
  'avgSpending' : IDL.Float64,
  'userId' : UserId,
  'maxSpending' : IDL.Float64,
  'activeHours' : IDL.Vec(IDL.Nat),
  'commonLocations' : IDL.Vec(IDL.Text),
  'totalTransactions' : IDL.Nat,
});

export const idlService = IDL.Service({
  'checkTransaction' : IDL.Func([CheckTransactionRequest], [Transaction], []),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getModelMetrics' : IDL.Func([], [ModelMetrics], ['query']),
  'getMyBehaviorProfile' : IDL.Func(
      [],
      [IDL.Opt(UserBehaviorProfile)],
      ['query'],
    ),
  'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TransactionMode = IDL.Variant({
    'ATM' : IDL.Null,
    'POS' : IDL.Null,
    'Web' : IDL.Null,
    'Mobile' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'OnlinePurchase' : IDL.Null,
    'Withdrawal' : IDL.Null,
    'Transfer' : IDL.Null,
    'Payment' : IDL.Null,
  });
  const MerchantCategory = IDL.Variant({
    'Food' : IDL.Null,
    'Bills' : IDL.Null,
    'Travel' : IDL.Null,
    'Shopping' : IDL.Null,
    'Others' : IDL.Null,
  });
  const DeviceType = IDL.Variant({
    'iOS' : IDL.Null,
    'Android' : IDL.Null,
    'Desktop' : IDL.Null,
  });
  const CheckTransactionRequest = IDL.Record({
    'transactionMode' : TransactionMode,
    'transactionType' : TransactionType,
    'merchantCategory' : MerchantCategory,
    'deviceType' : DeviceType,
    'amount' : IDL.Float64,
    'location' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const AutoFeatures = IDL.Record({
    'avgAmount' : IDL.Float64,
    'txCount24h' : IDL.Nat,
    'timeSinceLast' : IDL.Int,
    'prevLocation' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'fraudReasons' : IDL.Vec(IDL.Text),
    'transactionMode' : TransactionMode,
    'transactionType' : TransactionType,
    'userId' : UserId,
    'autoFeatures' : AutoFeatures,
    'merchantCategory' : MerchantCategory,
    'isFraud' : IDL.Bool,
    'timestamp' : Timestamp,
    'deviceType' : DeviceType,
    'confidence' : IDL.Float64,
    'amount' : IDL.Float64,
    'location' : IDL.Text,
    'riskScore' : IDL.Float64,
  });
  const DashboardStats = IDL.Record({
    'fraudCount' : IDL.Nat,
    'safeCount' : IDL.Nat,
    'recentTransactions' : IDL.Vec(Transaction),
    'fraudPercentage' : IDL.Float64,
    'totalTransactions' : IDL.Nat,
  });
  const ModelMetrics = IDL.Record({
    'trueNegatives' : IDL.Nat,
    'fraudCount' : IDL.Nat,
    'truePositives' : IDL.Nat,
    'f1Score' : IDL.Float64,
    'safeCount' : IDL.Nat,
    'precision' : IDL.Float64,
    'falseNegatives' : IDL.Nat,
    'falsePositives' : IDL.Nat,
    'totalTransactions' : IDL.Nat,
    'recall' : IDL.Float64,
    'accuracy' : IDL.Float64,
  });
  const UserBehaviorProfile = IDL.Record({
    'avgSpending' : IDL.Float64,
    'userId' : UserId,
    'maxSpending' : IDL.Float64,
    'activeHours' : IDL.Vec(IDL.Nat),
    'commonLocations' : IDL.Vec(IDL.Text),
    'totalTransactions' : IDL.Nat,
  });
  
  return IDL.Service({
    'checkTransaction' : IDL.Func([CheckTransactionRequest], [Transaction], []),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getModelMetrics' : IDL.Func([], [ModelMetrics], ['query']),
    'getMyBehaviorProfile' : IDL.Func(
        [],
        [IDL.Opt(UserBehaviorProfile)],
        ['query'],
      ),
    'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };