/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AutoFeatures {
  'avgAmount' : number,
  'txCount24h' : bigint,
  'timeSinceLast' : bigint,
  'prevLocation' : string,
}
export interface CheckTransactionRequest {
  'transactionMode' : TransactionMode,
  'transactionType' : TransactionType,
  'merchantCategory' : MerchantCategory,
  'deviceType' : DeviceType,
  'amount' : number,
  'location' : string,
}
export interface DashboardStats {
  'fraudCount' : bigint,
  'safeCount' : bigint,
  'recentTransactions' : Array<Transaction>,
  'fraudPercentage' : number,
  'totalTransactions' : bigint,
}
export type DeviceType = { 'iOS' : null } |
  { 'Android' : null } |
  { 'Desktop' : null };
export type MerchantCategory = { 'Food' : null } |
  { 'Bills' : null } |
  { 'Travel' : null } |
  { 'Shopping' : null } |
  { 'Others' : null };
export interface ModelMetrics {
  'trueNegatives' : bigint,
  'fraudCount' : bigint,
  'truePositives' : bigint,
  'f1Score' : number,
  'safeCount' : bigint,
  'precision' : number,
  'falseNegatives' : bigint,
  'falsePositives' : bigint,
  'totalTransactions' : bigint,
  'recall' : number,
  'accuracy' : number,
}
export type Timestamp = bigint;
export interface Transaction {
  'id' : string,
  'fraudReasons' : Array<string>,
  'transactionMode' : TransactionMode,
  'transactionType' : TransactionType,
  'userId' : UserId,
  'autoFeatures' : AutoFeatures,
  'merchantCategory' : MerchantCategory,
  'isFraud' : boolean,
  'timestamp' : Timestamp,
  'deviceType' : DeviceType,
  'confidence' : number,
  'amount' : number,
  'location' : string,
  'riskScore' : number,
}
export type TransactionMode = { 'ATM' : null } |
  { 'POS' : null } |
  { 'Web' : null } |
  { 'Mobile' : null };
export type TransactionType = { 'OnlinePurchase' : null } |
  { 'Withdrawal' : null } |
  { 'Transfer' : null } |
  { 'Payment' : null };
export interface UserBehaviorProfile {
  'avgSpending' : number,
  'userId' : UserId,
  'maxSpending' : number,
  'activeHours' : Array<bigint>,
  'commonLocations' : Array<string>,
  'totalTransactions' : bigint,
}
export type UserId = Principal;
export interface _SERVICE {
  'checkTransaction' : ActorMethod<[CheckTransactionRequest], Transaction>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getModelMetrics' : ActorMethod<[], ModelMetrics>,
  'getMyBehaviorProfile' : ActorMethod<[], [] | [UserBehaviorProfile]>,
  'getMyTransactions' : ActorMethod<[], Array<Transaction>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];