/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface CheckTransactionRequest {
    transactionMode: TransactionMode;
    transactionType: TransactionType;
    merchantCategory: MerchantCategory;
    deviceType: DeviceType;
    amount: number;
    location: string;
}
export interface ModelMetrics {
    trueNegatives: bigint;
    fraudCount: bigint;
    truePositives: bigint;
    f1Score: number;
    safeCount: bigint;
    precision: number;
    falseNegatives: bigint;
    falsePositives: bigint;
    totalTransactions: bigint;
    recall: number;
    accuracy: number;
}
export interface AutoFeatures {
    avgAmount: number;
    txCount24h: bigint;
    timeSinceLast: bigint;
    prevLocation: string;
}
export interface UserBehaviorProfile {
    avgSpending: number;
    userId: UserId;
    maxSpending: number;
    activeHours: Array<bigint>;
    commonLocations: Array<string>;
    totalTransactions: bigint;
}
export interface DashboardStats {
    fraudCount: bigint;
    safeCount: bigint;
    recentTransactions: Array<Transaction>;
    fraudPercentage: number;
    totalTransactions: bigint;
}
export interface Transaction {
    id: string;
    fraudReasons: Array<string>;
    transactionMode: TransactionMode;
    transactionType: TransactionType;
    userId: UserId;
    autoFeatures: AutoFeatures;
    merchantCategory: MerchantCategory;
    isFraud: boolean;
    timestamp: Timestamp;
    deviceType: DeviceType;
    confidence: number;
    amount: number;
    location: string;
    riskScore: number;
}
export enum DeviceType {
    iOS = "iOS",
    Android = "Android",
    Desktop = "Desktop"
}
export enum MerchantCategory {
    Food = "Food",
    Bills = "Bills",
    Travel = "Travel",
    Shopping = "Shopping",
    Others = "Others"
}
export enum TransactionMode {
    ATM = "ATM",
    POS = "POS",
    Web = "Web",
    Mobile = "Mobile"
}
export enum TransactionType {
    OnlinePurchase = "OnlinePurchase",
    Withdrawal = "Withdrawal",
    Transfer = "Transfer",
    Payment = "Payment"
}
export interface backendInterface {
    checkTransaction(req: CheckTransactionRequest): Promise<Transaction>;
    getDashboardStats(): Promise<DashboardStats>;
    getModelMetrics(): Promise<ModelMetrics>;
    getMyBehaviorProfile(): Promise<UserBehaviorProfile | null>;
    getMyTransactions(): Promise<Array<Transaction>>;
}
import type { AutoFeatures as _AutoFeatures, CheckTransactionRequest as _CheckTransactionRequest, DashboardStats as _DashboardStats, DeviceType as _DeviceType, MerchantCategory as _MerchantCategory, Timestamp as _Timestamp, Transaction as _Transaction, TransactionMode as _TransactionMode, TransactionType as _TransactionType, UserBehaviorProfile as _UserBehaviorProfile, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async checkTransaction(arg0: CheckTransactionRequest): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.checkTransaction(to_candid_CheckTransactionRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Transaction_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkTransaction(to_candid_CheckTransactionRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Transaction_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return from_candid_DashboardStats_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return from_candid_DashboardStats_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getModelMetrics(): Promise<ModelMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getModelMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModelMetrics();
            return result;
        }
    }
    async getMyBehaviorProfile(): Promise<UserBehaviorProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBehaviorProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBehaviorProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransactions();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransactions();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_DashboardStats_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardStats): DashboardStats {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_DeviceType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeviceType): DeviceType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_MerchantCategory_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MerchantCategory): MerchantCategory {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionMode_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionMode): TransactionMode {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserBehaviorProfile]): UserBehaviorProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    fraudReasons: Array<string>;
    transactionMode: _TransactionMode;
    transactionType: _TransactionType;
    userId: _UserId;
    autoFeatures: _AutoFeatures;
    merchantCategory: _MerchantCategory;
    isFraud: boolean;
    timestamp: _Timestamp;
    deviceType: _DeviceType;
    confidence: number;
    amount: number;
    location: string;
    riskScore: number;
}): {
    id: string;
    fraudReasons: Array<string>;
    transactionMode: TransactionMode;
    transactionType: TransactionType;
    userId: UserId;
    autoFeatures: AutoFeatures;
    merchantCategory: MerchantCategory;
    isFraud: boolean;
    timestamp: Timestamp;
    deviceType: DeviceType;
    confidence: number;
    amount: number;
    location: string;
    riskScore: number;
} {
    return {
        id: value.id,
        fraudReasons: value.fraudReasons,
        transactionMode: from_candid_TransactionMode_n13(_uploadFile, _downloadFile, value.transactionMode),
        transactionType: from_candid_TransactionType_n15(_uploadFile, _downloadFile, value.transactionType),
        userId: value.userId,
        autoFeatures: value.autoFeatures,
        merchantCategory: from_candid_MerchantCategory_n17(_uploadFile, _downloadFile, value.merchantCategory),
        isFraud: value.isFraud,
        timestamp: value.timestamp,
        deviceType: from_candid_DeviceType_n19(_uploadFile, _downloadFile, value.deviceType),
        confidence: value.confidence,
        amount: value.amount,
        location: value.location,
        riskScore: value.riskScore
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fraudCount: bigint;
    safeCount: bigint;
    recentTransactions: Array<_Transaction>;
    fraudPercentage: number;
    totalTransactions: bigint;
}): {
    fraudCount: bigint;
    safeCount: bigint;
    recentTransactions: Array<Transaction>;
    fraudPercentage: number;
    totalTransactions: bigint;
} {
    return {
        fraudCount: value.fraudCount,
        safeCount: value.safeCount,
        recentTransactions: from_candid_vec_n23(_uploadFile, _downloadFile, value.recentTransactions),
        fraudPercentage: value.fraudPercentage,
        totalTransactions: value.totalTransactions
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ATM: null;
} | {
    POS: null;
} | {
    Web: null;
} | {
    Mobile: null;
}): TransactionMode {
    return "ATM" in value ? TransactionMode.ATM : "POS" in value ? TransactionMode.POS : "Web" in value ? TransactionMode.Web : "Mobile" in value ? TransactionMode.Mobile : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    OnlinePurchase: null;
} | {
    Withdrawal: null;
} | {
    Transfer: null;
} | {
    Payment: null;
}): TransactionType {
    return "OnlinePurchase" in value ? TransactionType.OnlinePurchase : "Withdrawal" in value ? TransactionType.Withdrawal : "Transfer" in value ? TransactionType.Transfer : "Payment" in value ? TransactionType.Payment : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Food: null;
} | {
    Bills: null;
} | {
    Travel: null;
} | {
    Shopping: null;
} | {
    Others: null;
}): MerchantCategory {
    return "Food" in value ? MerchantCategory.Food : "Bills" in value ? MerchantCategory.Bills : "Travel" in value ? MerchantCategory.Travel : "Shopping" in value ? MerchantCategory.Shopping : "Others" in value ? MerchantCategory.Others : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    iOS: null;
} | {
    Android: null;
} | {
    Desktop: null;
}): DeviceType {
    return "iOS" in value ? DeviceType.iOS : "Android" in value ? DeviceType.Android : "Desktop" in value ? DeviceType.Desktop : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n11(_uploadFile, _downloadFile, x));
}
function to_candid_CheckTransactionRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CheckTransactionRequest): _CheckTransactionRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_DeviceType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeviceType): _DeviceType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_MerchantCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MerchantCategory): _MerchantCategory {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionMode_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionMode): _TransactionMode {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transactionMode: TransactionMode;
    transactionType: TransactionType;
    merchantCategory: MerchantCategory;
    deviceType: DeviceType;
    amount: number;
    location: string;
}): {
    transactionMode: _TransactionMode;
    transactionType: _TransactionType;
    merchantCategory: _MerchantCategory;
    deviceType: _DeviceType;
    amount: number;
    location: string;
} {
    return {
        transactionMode: to_candid_TransactionMode_n3(_uploadFile, _downloadFile, value.transactionMode),
        transactionType: to_candid_TransactionType_n5(_uploadFile, _downloadFile, value.transactionType),
        merchantCategory: to_candid_MerchantCategory_n7(_uploadFile, _downloadFile, value.merchantCategory),
        deviceType: to_candid_DeviceType_n9(_uploadFile, _downloadFile, value.deviceType),
        amount: value.amount,
        location: value.location
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeviceType): {
    iOS: null;
} | {
    Android: null;
} | {
    Desktop: null;
} {
    return value == DeviceType.iOS ? {
        iOS: null
    } : value == DeviceType.Android ? {
        Android: null
    } : value == DeviceType.Desktop ? {
        Desktop: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionMode): {
    ATM: null;
} | {
    POS: null;
} | {
    Web: null;
} | {
    Mobile: null;
} {
    return value == TransactionMode.ATM ? {
        ATM: null
    } : value == TransactionMode.POS ? {
        POS: null
    } : value == TransactionMode.Web ? {
        Web: null
    } : value == TransactionMode.Mobile ? {
        Mobile: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    OnlinePurchase: null;
} | {
    Withdrawal: null;
} | {
    Transfer: null;
} | {
    Payment: null;
} {
    return value == TransactionType.OnlinePurchase ? {
        OnlinePurchase: null
    } : value == TransactionType.Withdrawal ? {
        Withdrawal: null
    } : value == TransactionType.Transfer ? {
        Transfer: null
    } : value == TransactionType.Payment ? {
        Payment: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MerchantCategory): {
    Food: null;
} | {
    Bills: null;
} | {
    Travel: null;
} | {
    Shopping: null;
} | {
    Others: null;
} {
    return value == MerchantCategory.Food ? {
        Food: null
    } : value == MerchantCategory.Bills ? {
        Bills: null
    } : value == MerchantCategory.Travel ? {
        Travel: null
    } : value == MerchantCategory.Shopping ? {
        Shopping: null
    } : value == MerchantCategory.Others ? {
        Others: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
